#!/usr/bin/env python3
"""
Comprehensive Reference Populations Database
Based on AncestryDNA's 146 regions (2025 update)
"""

# =============================================================================
# REFERENCE POPULATIONS (146 REGIONS - AncestryDNA 2025 Level)
# =============================================================================

REFERENCE_POPULATIONS = {
    # =========================================================================
    # EUROPE - British Isles & Ireland (15 regions)
    # =========================================================================
    'England_Northwestern': {
        'display_name': 'England & Northwestern Europe',
        'parent': 'British_Isles',
        'countries': ['England', 'Wales'],
        'pc_coords': [0.022, -0.016, 0.002, 0.001],
        'historical': 'Anglo-Saxon, Norman, and Celtic heritage',
    },
    'Central_Scotland_Northern_Ireland': {
        'display_name': 'Central Scotland & Northern Ireland',
        'parent': 'British_Isles',
        'countries': ['Scotland', 'Northern Ireland'],
        'pc_coords': [0.026, -0.021, 0.005, 0.002],
        'historical': 'Ulster Scots and Scottish Lowlander heritage',
    },
    'Hebrides_Western_Highlands': {
        'display_name': 'Hebrides & Western Highlands, Scotland',
        'parent': 'British_Isles',
        'countries': ['Scotland'],
        'pc_coords': [0.028, -0.024, 0.007, 0.003],
        'historical': 'Gaelic Highland and Island heritage with Norse influence',
    },
    'Northern_Wales_Northwest_England': {
        'display_name': 'Northern Wales & North West England',
        'parent': 'British_Isles',
        'countries': ['Wales', 'England'],
        'pc_coords': [0.024, -0.019, 0.004, 0.002],
        'historical': 'Welsh and Northern English heritage',
    },
    'Southern_Wales': {
        'display_name': 'Southern Wales',
        'parent': 'British_Isles',
        'countries': ['Wales'],
        'pc_coords': [0.023, -0.018, 0.003, 0.001],
        'historical': 'South Welsh Celtic heritage',
    },
    'Devon_Somerset': {
        'display_name': 'Devon & Somerset',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.021, -0.015, 0.001, 0.000],
        'historical': 'West Country English heritage',
    },
    'Cornwall': {
        'display_name': 'Cornwall',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.020, -0.014, 0.000, -0.001],
        'historical': 'Cornish Celtic heritage',
    },
    'East_Midlands': {
        'display_name': 'East Midlands',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.022, -0.016, 0.002, 0.001],
        'historical': 'Anglo-Saxon Mercian heritage',
    },
    'Northern_England': {
        'display_name': 'Northern England',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.024, -0.018, 0.004, 0.002],
        'historical': 'Anglo-Saxon and Viking Danelaw heritage',
    },
    'Southeastern_England': {
        'display_name': 'Southeastern England',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.021, -0.015, 0.001, 0.000],
        'historical': 'Anglo-Saxon and Norman heritage',
    },
    'West_Midlands': {
        'display_name': 'West Midlands',
        'parent': 'British_Isles',
        'countries': ['England'],
        'pc_coords': [0.022, -0.016, 0.002, 0.001],
        'historical': 'Anglo-Saxon heritage',
    },
    'Ireland': {
        'display_name': 'Ireland',
        'parent': 'British_Isles',
        'countries': ['Ireland'],
        'pc_coords': [0.027, -0.023, 0.006, 0.003],
        'historical': 'Gaelic Irish heritage',
    },
    'Munster_Ireland': {
        'display_name': 'Munster, Ireland',
        'parent': 'Ireland',
        'countries': ['Ireland'],
        'pc_coords': [0.028, -0.024, 0.007, 0.003],
        'historical': 'Southern Irish heritage',
    },
    'Connacht_Ireland': {
        'display_name': 'Connacht, Ireland',
        'parent': 'Ireland',
        'countries': ['Ireland'],
        'pc_coords': [0.029, -0.025, 0.008, 0.004],
        'historical': 'Western Irish heritage',
    },
    'Leinster_Ireland': {
        'display_name': 'Leinster, Ireland',
        'parent': 'Ireland',
        'countries': ['Ireland'],
        'pc_coords': [0.026, -0.022, 0.005, 0.002],
        'historical': 'Eastern Irish heritage with Viking influence',
    },

    # =========================================================================
    # EUROPE - Scandinavia (8 regions)
    # =========================================================================
    'Norway': {
        'display_name': 'Norway',
        'parent': 'Scandinavian',
        'countries': ['Norway'],
        'pc_coords': [0.032, -0.030, 0.012, 0.005],
        'historical': 'Norwegian Viking heritage',
    },
    'Sweden': {
        'display_name': 'Sweden',
        'parent': 'Scandinavian',
        'countries': ['Sweden'],
        'pc_coords': [0.029, -0.026, 0.009, 0.004],
        'historical': 'Swedish Viking heritage',
    },
    'Denmark': {
        'display_name': 'Denmark',
        'parent': 'Scandinavian',
        'countries': ['Denmark'],
        'pc_coords': [0.026, -0.022, 0.006, 0.002],
        'historical': 'Danish Viking heritage',
    },
    'Iceland': {
        'display_name': 'Iceland',
        'parent': 'Scandinavian',
        'countries': ['Iceland'],
        'pc_coords': [0.030, -0.028, 0.010, 0.004],
        'historical': 'Norse settlement with Irish/Scottish admixture',
    },
    'Finland': {
        'display_name': 'Finland',
        'parent': 'Scandinavian',
        'countries': ['Finland'],
        'pc_coords': [0.035, -0.018, 0.028, 0.012],
        'historical': 'Finno-Ugric heritage with Scandinavian influence',
    },
    'Sami': {
        'display_name': 'Sami',
        'parent': 'Scandinavian',
        'countries': ['Norway', 'Sweden', 'Finland'],
        'pc_coords': [0.038, -0.015, 0.035, 0.015],
        'historical': 'Indigenous Sami reindeer herders',
    },
    'Faroe_Islands': {
        'display_name': 'Faroe Islands',
        'parent': 'Scandinavian',
        'countries': ['Denmark'],
        'pc_coords': [0.031, -0.029, 0.011, 0.005],
        'historical': 'Norse settlement heritage',
    },
    'Aland_Islands': {
        'display_name': 'Åland Islands',
        'parent': 'Scandinavian',
        'countries': ['Finland'],
        'pc_coords': [0.028, -0.024, 0.008, 0.003],
        'historical': 'Swedish-speaking Finns',
    },

    # =========================================================================
    # EUROPE - Germanic (10 regions)
    # =========================================================================
    'Northwestern_Germany': {
        'display_name': 'Northwestern Germany',
        'parent': 'Germanic',
        'countries': ['Germany'],
        'pc_coords': [0.020, -0.012, 0.003, 0.001],
        'historical': 'Low German and Frisian heritage',
    },
    'Southern_Germanic': {
        'display_name': 'Southern Germanic Europe',
        'parent': 'Germanic',
        'countries': ['Germany', 'Austria', 'Switzerland'],
        'pc_coords': [0.016, -0.006, -0.001, -0.001],
        'historical': 'Bavarian, Austrian, and Swiss German heritage',
    },
    'North_Central_Europe': {
        'display_name': 'North Central Europe',
        'parent': 'Germanic',
        'countries': ['Germany', 'Poland'],
        'pc_coords': [0.018, -0.008, 0.008, 0.003],
        'historical': 'Eastern German and Western Polish heritage',
    },
    'Netherlands': {
        'display_name': 'The Netherlands',
        'parent': 'Germanic',
        'countries': ['Netherlands'],
        'pc_coords': [0.021, -0.014, 0.002, 0.001],
        'historical': 'Dutch heritage',
    },
    'Belgium': {
        'display_name': 'Belgium',
        'parent': 'Germanic',
        'countries': ['Belgium'],
        'pc_coords': [0.019, -0.011, 0.001, 0.000],
        'historical': 'Flemish and Walloon heritage',
    },
    'Luxembourg': {
        'display_name': 'Luxembourg',
        'parent': 'Germanic',
        'countries': ['Luxembourg'],
        'pc_coords': [0.017, -0.008, 0.000, -0.001],
        'historical': 'Luxembourgish heritage',
    },
    'Switzerland': {
        'display_name': 'Switzerland',
        'parent': 'Germanic',
        'countries': ['Switzerland'],
        'pc_coords': [0.015, -0.005, -0.002, -0.001],
        'historical': 'Swiss German, French, and Italian heritage',
    },
    'Austria': {
        'display_name': 'Austria',
        'parent': 'Germanic',
        'countries': ['Austria'],
        'pc_coords': [0.014, -0.004, -0.001, -0.002],
        'historical': 'Austrian heritage',
    },
    'Alsace_Lorraine': {
        'display_name': 'Alsace-Lorraine',
        'parent': 'Germanic',
        'countries': ['France'],
        'pc_coords': [0.016, -0.007, 0.000, -0.001],
        'historical': 'French-German border heritage',
    },
    'Russian_Germans': {
        'display_name': 'Russian Germans',
        'parent': 'Germanic',
        'countries': ['Russia', 'Kazakhstan'],
        'pc_coords': [0.018, -0.005, 0.015, 0.006],
        'historical': 'Volga German and Black Sea German heritage',
    },

    # =========================================================================
    # EUROPE - France (6 regions)
    # =========================================================================
    'Metropolitan_France': {
        'display_name': 'Metropolitan France',
        'parent': 'French',
        'countries': ['France'],
        'pc_coords': [0.014, -0.006, -0.003, -0.001],
        'historical': 'Central French heritage',
    },
    'Brittany': {
        'display_name': 'Brittany, France',
        'parent': 'French',
        'countries': ['France'],
        'pc_coords': [0.018, -0.012, 0.001, 0.001],
        'historical': 'Celtic Breton heritage',
    },
    'Normandy': {
        'display_name': 'Normandy',
        'parent': 'French',
        'countries': ['France'],
        'pc_coords': [0.017, -0.010, 0.000, 0.000],
        'historical': 'Norman Viking heritage',
    },
    'Quebec': {
        'display_name': 'Quebec',
        'parent': 'French',
        'countries': ['Canada'],
        'pc_coords': [0.015, -0.007, -0.002, 0.000],
        'historical': 'French Canadian heritage',
    },
    'Acadia': {
        'display_name': 'Acadia',
        'parent': 'French',
        'countries': ['Canada'],
        'pc_coords': [0.016, -0.008, -0.001, 0.001],
        'historical': 'Acadian French heritage',
    },
    'Occitanie': {
        'display_name': 'Occitanie (Southern France)',
        'parent': 'French',
        'countries': ['France'],
        'pc_coords': [0.010, -0.002, -0.006, -0.002],
        'historical': 'Occitan heritage',
    },

    # =========================================================================
    # EUROPE - Iberian Peninsula (12 regions)
    # =========================================================================
    'Spain': {
        'display_name': 'Spain',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.005, 0.008, -0.010, -0.003],
        'historical': 'Central Spanish heritage',
    },
    'Northern_Spain': {
        'display_name': 'Northern Spain',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.008, 0.005, -0.008, -0.002],
        'historical': 'Asturian and Cantabrian heritage',
    },
    'Basque': {
        'display_name': 'Basque',
        'parent': 'Iberian',
        'countries': ['Spain', 'France'],
        'pc_coords': [0.010, 0.004, -0.015, -0.002],
        'historical': 'Pre-Indo-European Basque isolate',
    },
    'Catalonia': {
        'display_name': 'Catalonia',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.006, 0.006, -0.008, -0.002],
        'historical': 'Catalan heritage',
    },
    'Galicia': {
        'display_name': 'Galicia',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.009, 0.006, -0.009, -0.002],
        'historical': 'Celtic-Iberian Galician heritage',
    },
    'Andalusia': {
        'display_name': 'Andalusia',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.002, 0.012, -0.012, -0.004],
        'historical': 'Moorish and Southern Spanish heritage',
    },
    'Portugal': {
        'display_name': 'Portugal',
        'parent': 'Iberian',
        'countries': ['Portugal'],
        'pc_coords': [0.004, 0.010, -0.011, -0.003],
        'historical': 'Portuguese heritage',
    },
    'Azores': {
        'display_name': 'Azores',
        'parent': 'Iberian',
        'countries': ['Portugal'],
        'pc_coords': [0.006, 0.012, -0.010, -0.003],
        'historical': 'Portuguese Atlantic island heritage',
    },
    'Madeira': {
        'display_name': 'Madeira',
        'parent': 'Iberian',
        'countries': ['Portugal'],
        'pc_coords': [0.005, 0.014, -0.011, -0.004],
        'historical': 'Portuguese Atlantic island heritage',
    },
    'Canary_Islands': {
        'display_name': 'Canary Islands',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.000, 0.018, -0.015, -0.005],
        'historical': 'Guanche and Spanish heritage',
    },
    'Gibraltar': {
        'display_name': 'Gibraltar',
        'parent': 'Iberian',
        'countries': ['Gibraltar'],
        'pc_coords': [0.003, 0.011, -0.011, -0.003],
        'historical': 'British-Spanish mixed heritage',
    },
    'Balearic_Islands': {
        'display_name': 'Balearic Islands',
        'parent': 'Iberian',
        'countries': ['Spain'],
        'pc_coords': [0.004, 0.009, -0.009, -0.003],
        'historical': 'Catalan-Spanish island heritage',
    },

    # =========================================================================
    # EUROPE - Italy (10 regions)
    # =========================================================================
    'Northern_Italy': {
        'display_name': 'Northern Italy',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.008, 0.006, -0.004, -0.002],
        'historical': 'Lombard and Celtic-Italic heritage',
    },
    'Northwestern_Italy': {
        'display_name': 'Northwestern Italy',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.009, 0.005, -0.003, -0.001],
        'historical': 'Piedmontese and Ligurian heritage',
    },
    'Northeastern_Italy': {
        'display_name': 'Northeastern Italy',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.007, 0.007, -0.003, -0.002],
        'historical': 'Venetian and Friulian heritage',
    },
    'Central_Italy': {
        'display_name': 'Central Italy',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.004, 0.012, -0.006, -0.003],
        'historical': 'Tuscan and Umbrian heritage',
    },
    'Southern_Italy': {
        'display_name': 'Southern Italy',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [-0.002, 0.020, -0.008, -0.005],
        'historical': 'Greek colonization and Norman heritage',
    },
    'Sicily': {
        'display_name': 'Sicily',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [-0.005, 0.025, -0.010, -0.006],
        'historical': 'Greek, Arabic, and Norman heritage',
    },
    'Sardinia': {
        'display_name': 'Sardinia',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.000, 0.015, -0.020, -0.005],
        'historical': 'Ancient Nuragic isolate heritage',
    },
    'Malta': {
        'display_name': 'Malta',
        'parent': 'Italian',
        'countries': ['Malta'],
        'pc_coords': [-0.008, 0.028, -0.012, -0.008],
        'historical': 'Phoenician, Arabic, and Italian heritage',
    },
    'Calabria': {
        'display_name': 'Calabria',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [-0.004, 0.022, -0.009, -0.005],
        'historical': 'Magna Graecia heritage',
    },
    'Naples_Campania': {
        'display_name': 'Naples & Campania',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [-0.001, 0.018, -0.007, -0.004],
        'historical': 'Greek and Roman heritage',
    },

    # =========================================================================
    # EUROPE - Greece & Balkans (15 regions)
    # =========================================================================
    'Northern_Central_Greece': {
        'display_name': 'Northern & Central Greece',
        'parent': 'Greek',
        'countries': ['Greece'],
        'pc_coords': [-0.010, 0.028, -0.005, -0.008],
        'historical': 'Macedonian and Thessalian heritage',
    },
    'Southern_Greece': {
        'display_name': 'Southern Greece',
        'parent': 'Greek',
        'countries': ['Greece'],
        'pc_coords': [-0.012, 0.030, -0.006, -0.009],
        'historical': 'Peloponnesian heritage',
    },
    'Crete': {
        'display_name': 'Crete',
        'parent': 'Greek',
        'countries': ['Greece'],
        'pc_coords': [-0.015, 0.035, -0.008, -0.010],
        'historical': 'Minoan-descended Cretan heritage',
    },
    'Aegean_Islands': {
        'display_name': 'Aegean Islands',
        'parent': 'Greek',
        'countries': ['Greece'],
        'pc_coords': [-0.013, 0.032, -0.007, -0.009],
        'historical': 'Greek island heritage',
    },
    'Ionian_Islands': {
        'display_name': 'Ionian Islands',
        'parent': 'Greek',
        'countries': ['Greece'],
        'pc_coords': [-0.008, 0.026, -0.004, -0.007],
        'historical': 'Venetian-influenced Greek heritage',
    },
    'Cyprus': {
        'display_name': 'Cyprus',
        'parent': 'Greek',
        'countries': ['Cyprus'],
        'pc_coords': [-0.018, 0.038, -0.006, -0.012],
        'historical': 'Greek Cypriot heritage',
    },
    'Albania': {
        'display_name': 'Albania',
        'parent': 'Balkan',
        'countries': ['Albania'],
        'pc_coords': [-0.006, 0.022, -0.002, -0.006],
        'historical': 'Illyrian-descended Albanian heritage',
    },
    'Northwestern_Balkans': {
        'display_name': 'Northwestern Balkans',
        'parent': 'Balkan',
        'countries': ['Croatia', 'Slovenia'],
        'pc_coords': [-0.002, 0.014, 0.004, -0.003],
        'historical': 'Croatian and Slovenian heritage',
    },
    'Southwestern_Balkans': {
        'display_name': 'Southwestern Balkans',
        'parent': 'Balkan',
        'countries': ['Bosnia', 'Montenegro'],
        'pc_coords': [-0.004, 0.018, 0.002, -0.004],
        'historical': 'Bosnian and Montenegrin heritage',
    },
    'Western_Balkans': {
        'display_name': 'Western Balkans',
        'parent': 'Balkan',
        'countries': ['Serbia', 'Kosovo'],
        'pc_coords': [-0.005, 0.016, 0.006, -0.004],
        'historical': 'Serbian heritage',
    },
    'Romania': {
        'display_name': 'Romania',
        'parent': 'Balkan',
        'countries': ['Romania', 'Moldova'],
        'pc_coords': [-0.003, 0.012, 0.012, -0.002],
        'historical': 'Dacian and Roman heritage',
    },
    'Bulgaria': {
        'display_name': 'Bulgaria',
        'parent': 'Balkan',
        'countries': ['Bulgaria'],
        'pc_coords': [-0.006, 0.018, 0.008, -0.005],
        'historical': 'Thracian and Slavic heritage',
    },
    'North_Macedonia': {
        'display_name': 'North Macedonia',
        'parent': 'Balkan',
        'countries': ['North Macedonia'],
        'pc_coords': [-0.007, 0.020, 0.005, -0.006],
        'historical': 'South Slavic heritage',
    },
    'Slovenia': {
        'display_name': 'Slovenia',
        'parent': 'Balkan',
        'countries': ['Slovenia'],
        'pc_coords': [0.000, 0.010, 0.005, -0.002],
        'historical': 'Alpine Slavic heritage',
    },
    'Eastern_European_Roma': {
        'display_name': 'Eastern European Roma',
        'parent': 'Balkan',
        'countries': ['Multiple'],
        'pc_coords': [-0.015, 0.025, 0.015, -0.008],
        'historical': 'Roma/Romani heritage from South Asia',
    },

    # =========================================================================
    # EUROPE - Eastern Europe (12 regions)
    # =========================================================================
    'Poland': {
        'display_name': 'Poland',
        'parent': 'Eastern_European',
        'countries': ['Poland'],
        'pc_coords': [0.014, 0.004, 0.014, 0.005],
        'historical': 'Polish Slavic heritage',
    },
    'Ukraine': {
        'display_name': 'Ukraine',
        'parent': 'Eastern_European',
        'countries': ['Ukraine'],
        'pc_coords': [0.012, 0.008, 0.018, 0.006],
        'historical': 'Ukrainian Slavic heritage',
    },
    'Belarus': {
        'display_name': 'Belarus',
        'parent': 'Eastern_European',
        'countries': ['Belarus'],
        'pc_coords': [0.015, 0.006, 0.016, 0.006],
        'historical': 'Belarusian Slavic heritage',
    },
    'Russia': {
        'display_name': 'Russia',
        'parent': 'Eastern_European',
        'countries': ['Russia'],
        'pc_coords': [0.018, 0.010, 0.022, 0.008],
        'historical': 'Russian Slavic heritage',
    },
    'Baltic_States': {
        'display_name': 'Baltic States',
        'parent': 'Eastern_European',
        'countries': ['Lithuania', 'Latvia', 'Estonia'],
        'pc_coords': [0.020, 0.002, 0.020, 0.008],
        'historical': 'Baltic heritage',
    },
    'Lithuania': {
        'display_name': 'Lithuania',
        'parent': 'Eastern_European',
        'countries': ['Lithuania'],
        'pc_coords': [0.019, 0.003, 0.018, 0.007],
        'historical': 'Lithuanian Baltic heritage',
    },
    'Latvia': {
        'display_name': 'Latvia',
        'parent': 'Eastern_European',
        'countries': ['Latvia'],
        'pc_coords': [0.021, 0.002, 0.019, 0.008],
        'historical': 'Latvian Baltic heritage',
    },
    'Estonia': {
        'display_name': 'Estonia',
        'parent': 'Eastern_European',
        'countries': ['Estonia'],
        'pc_coords': [0.024, 0.000, 0.024, 0.010],
        'historical': 'Estonian Finno-Ugric heritage',
    },
    'Czech_Republic': {
        'display_name': 'Czech Republic',
        'parent': 'Eastern_European',
        'countries': ['Czech Republic'],
        'pc_coords': [0.012, 0.000, 0.008, 0.003],
        'historical': 'Czech Slavic heritage',
    },
    'Slovakia': {
        'display_name': 'Slovakia',
        'parent': 'Eastern_European',
        'countries': ['Slovakia'],
        'pc_coords': [0.010, 0.004, 0.010, 0.004],
        'historical': 'Slovak Slavic heritage',
    },
    'Hungary': {
        'display_name': 'Hungary',
        'parent': 'Eastern_European',
        'countries': ['Hungary'],
        'pc_coords': [0.006, 0.008, 0.012, 0.002],
        'historical': 'Magyar heritage with Slavic influence',
    },
    'Carpathian': {
        'display_name': 'Carpathian Region',
        'parent': 'Eastern_European',
        'countries': ['Ukraine', 'Romania', 'Poland'],
        'pc_coords': [0.008, 0.010, 0.015, 0.004],
        'historical': 'Carpathian mountain heritage',
    },

    # =========================================================================
    # EUROPE - Jewish (4 regions)
    # =========================================================================
    'Ashkenazi_Jewish': {
        'display_name': 'Ashkenazi Jewish',
        'parent': 'Jewish',
        'countries': ['Multiple'],
        'pc_coords': [0.002, 0.018, -0.005, -0.012],
        'historical': 'Central/Eastern European Jewish heritage',
    },
    'Sephardic_Jewish': {
        'display_name': 'Sephardic Jewish',
        'parent': 'Jewish',
        'countries': ['Multiple'],
        'pc_coords': [-0.005, 0.025, -0.010, -0.010],
        'historical': 'Iberian Jewish heritage',
    },
    'Mizrahi_Jewish': {
        'display_name': 'Mizrahi Jewish',
        'parent': 'Jewish',
        'countries': ['Multiple'],
        'pc_coords': [-0.015, 0.035, -0.005, -0.015],
        'historical': 'Middle Eastern Jewish heritage',
    },
    'Ethiopian_Jewish': {
        'display_name': 'Ethiopian Jewish',
        'parent': 'Jewish',
        'countries': ['Ethiopia'],
        'pc_coords': [-0.050, 0.010, 0.000, 0.020],
        'historical': 'Beta Israel heritage',
    },

    # =========================================================================
    # MIDDLE EAST (15 regions)
    # =========================================================================
    'Levantine': {
        'display_name': 'Levantine',
        'parent': 'Middle_Eastern',
        'countries': ['Lebanon', 'Syria', 'Jordan', 'Palestine', 'Israel'],
        'pc_coords': [-0.018, 0.038, -0.008, -0.015],
        'historical': 'Phoenician and Aramaic heritage',
    },
    'Lebanese': {
        'display_name': 'Lebanon',
        'parent': 'Middle_Eastern',
        'countries': ['Lebanon'],
        'pc_coords': [-0.015, 0.035, -0.006, -0.012],
        'historical': 'Phoenician heritage',
    },
    'Syrian': {
        'display_name': 'Syria',
        'parent': 'Middle_Eastern',
        'countries': ['Syria'],
        'pc_coords': [-0.018, 0.038, -0.007, -0.014],
        'historical': 'Aramaic heritage',
    },
    'Palestinian': {
        'display_name': 'Palestinian',
        'parent': 'Middle_Eastern',
        'countries': ['Palestine', 'Israel'],
        'pc_coords': [-0.016, 0.036, -0.006, -0.013],
        'historical': 'Canaanite heritage',
    },
    'Arabian_Peninsula': {
        'display_name': 'Arabian Peninsula',
        'parent': 'Middle_Eastern',
        'countries': ['Saudi Arabia', 'Yemen', 'UAE', 'Oman', 'Qatar', 'Kuwait', 'Bahrain'],
        'pc_coords': [-0.028, 0.048, -0.015, -0.022],
        'historical': 'Bedouin and ancient Arabian heritage',
    },
    'Yemen': {
        'display_name': 'Yemen',
        'parent': 'Middle_Eastern',
        'countries': ['Yemen'],
        'pc_coords': [-0.032, 0.045, -0.012, -0.020],
        'historical': 'Ancient Yemeni heritage',
    },
    'Iraq': {
        'display_name': 'Iraq',
        'parent': 'Middle_Eastern',
        'countries': ['Iraq'],
        'pc_coords': [-0.022, 0.042, -0.005, -0.016],
        'historical': 'Mesopotamian heritage',
    },
    'Iran_Persia': {
        'display_name': 'Iran/Persia',
        'parent': 'Middle_Eastern',
        'countries': ['Iran'],
        'pc_coords': [-0.020, 0.042, 0.008, -0.012],
        'historical': 'Ancient Persian heritage',
    },
    'Kurdish': {
        'display_name': 'Kurdish',
        'parent': 'Middle_Eastern',
        'countries': ['Turkey', 'Iraq', 'Iran', 'Syria'],
        'pc_coords': [-0.018, 0.040, 0.005, -0.010],
        'historical': 'Kurdish heritage',
    },
    'Turkey': {
        'display_name': 'Turkey',
        'parent': 'Middle_Eastern',
        'countries': ['Turkey'],
        'pc_coords': [-0.012, 0.030, 0.002, -0.008],
        'historical': 'Anatolian with Turkic heritage',
    },
    'Caucasus': {
        'display_name': 'Caucasus',
        'parent': 'Middle_Eastern',
        'countries': ['Georgia', 'Armenia', 'Azerbaijan'],
        'pc_coords': [-0.010, 0.032, 0.010, -0.006],
        'historical': 'Caucasian heritage',
    },
    'Armenia': {
        'display_name': 'Armenia',
        'parent': 'Middle_Eastern',
        'countries': ['Armenia'],
        'pc_coords': [-0.012, 0.034, 0.008, -0.008],
        'historical': 'Ancient Armenian heritage',
    },
    'Georgia': {
        'display_name': 'Georgia',
        'parent': 'Middle_Eastern',
        'countries': ['Georgia'],
        'pc_coords': [-0.008, 0.030, 0.012, -0.005],
        'historical': 'Georgian Kartvelian heritage',
    },
    'Azerbaijan': {
        'display_name': 'Azerbaijan',
        'parent': 'Middle_Eastern',
        'countries': ['Azerbaijan'],
        'pc_coords': [-0.010, 0.035, 0.015, -0.006],
        'historical': 'Azerbaijani Turkic heritage',
    },
    'Central_Asia': {
        'display_name': 'Central Asia',
        'parent': 'Middle_Eastern',
        'countries': ['Kazakhstan', 'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan', 'Tajikistan'],
        'pc_coords': [-0.025, 0.020, 0.035, 0.000],
        'historical': 'Turkic and Persian heritage',
    },

    # =========================================================================
    # AFRICA (25 regions)
    # =========================================================================
    'Nigeria': {
        'display_name': 'Nigeria',
        'parent': 'West_African',
        'countries': ['Nigeria'],
        'pc_coords': [-0.088, -0.028, -0.022, 0.006],
        'historical': 'Yoruba, Igbo, and Hausa ethnic groups',
    },
    'Ghana': {
        'display_name': 'Ghana',
        'parent': 'West_African',
        'countries': ['Ghana'],
        'pc_coords': [-0.085, -0.025, -0.020, 0.005],
        'historical': 'Akan, Ewe, and Ga-Adangbe peoples',
    },
    'Senegal': {
        'display_name': 'Senegal',
        'parent': 'West_African',
        'countries': ['Senegal', 'Gambia'],
        'pc_coords': [-0.082, -0.030, -0.024, 0.007],
        'historical': 'Wolof, Fula, and Serer peoples',
    },
    'Mali': {
        'display_name': 'Mali',
        'parent': 'West_African',
        'countries': ['Mali'],
        'pc_coords': [-0.080, -0.028, -0.022, 0.006],
        'historical': 'Mandinka and Bambara heritage',
    },
    'Ivory_Coast': {
        'display_name': "Côte d'Ivoire",
        'parent': 'West_African',
        'countries': ["Côte d'Ivoire"],
        'pc_coords': [-0.086, -0.026, -0.021, 0.005],
        'historical': 'Baoulé, Bété, and Sénoufo peoples',
    },
    'Cameroon': {
        'display_name': 'Cameroon, Congo & Western Bantu Peoples',
        'parent': 'Central_African',
        'countries': ['Cameroon', 'Congo'],
        'pc_coords': [-0.090, -0.022, -0.018, 0.008],
        'historical': 'Bantu and semi-Bantu heritage',
    },
    'Congo': {
        'display_name': 'Congo & Southern Bantu Peoples',
        'parent': 'Central_African',
        'countries': ['DRC', 'Republic of Congo', 'Angola'],
        'pc_coords': [-0.092, -0.020, -0.015, 0.010],
        'historical': 'Bantu expansion heritage',
    },
    'Benin_Togo': {
        'display_name': 'Benin & Togo',
        'parent': 'West_African',
        'countries': ['Benin', 'Togo'],
        'pc_coords': [-0.087, -0.027, -0.021, 0.006],
        'historical': 'Fon, Ewe, and Yoruba peoples',
    },
    'Kenya': {
        'display_name': 'Kenya',
        'parent': 'East_African',
        'countries': ['Kenya'],
        'pc_coords': [-0.075, -0.012, -0.008, 0.015],
        'historical': 'Bantu, Nilotic, and Cushitic peoples',
    },
    'Tanzania': {
        'display_name': 'Tanzania',
        'parent': 'East_African',
        'countries': ['Tanzania'],
        'pc_coords': [-0.078, -0.015, -0.010, 0.012],
        'historical': 'Bantu and Swahili heritage',
    },
    'Uganda': {
        'display_name': 'Uganda',
        'parent': 'East_African',
        'countries': ['Uganda'],
        'pc_coords': [-0.076, -0.014, -0.009, 0.014],
        'historical': 'Bantu and Nilotic peoples',
    },
    'Ethiopia_Eritrea': {
        'display_name': 'Ethiopia & Eritrea',
        'parent': 'East_African',
        'countries': ['Ethiopia', 'Eritrea'],
        'pc_coords': [-0.060, 0.008, 0.002, 0.020],
        'historical': 'Ancient Semitic and Cushitic heritage',
    },
    'Somalia': {
        'display_name': 'Somalia',
        'parent': 'East_African',
        'countries': ['Somalia'],
        'pc_coords': [-0.058, 0.012, 0.005, 0.022],
        'historical': 'Somali Cushitic heritage',
    },
    'Sudan': {
        'display_name': 'Sudan',
        'parent': 'East_African',
        'countries': ['Sudan', 'South Sudan'],
        'pc_coords': [-0.065, 0.000, -0.002, 0.018],
        'historical': 'Nubian and Nilotic heritage',
    },
    'South_Africa': {
        'display_name': 'South Africa',
        'parent': 'Southern_African',
        'countries': ['South Africa'],
        'pc_coords': [-0.095, -0.032, -0.012, 0.004],
        'historical': 'Bantu, Khoisan, and mixed heritage',
    },
    'Zimbabwe': {
        'display_name': 'Zimbabwe',
        'parent': 'Southern_African',
        'countries': ['Zimbabwe'],
        'pc_coords': [-0.092, -0.028, -0.010, 0.006],
        'historical': 'Shona and Ndebele heritage',
    },
    'Mozambique': {
        'display_name': 'Mozambique',
        'parent': 'Southern_African',
        'countries': ['Mozambique'],
        'pc_coords': [-0.088, -0.025, -0.008, 0.008],
        'historical': 'Makua and Tsonga heritage',
    },
    'Madagascar': {
        'display_name': 'Madagascar',
        'parent': 'East_African',
        'countries': ['Madagascar'],
        'pc_coords': [-0.070, -0.035, 0.025, 0.000],
        'historical': 'Austronesian and African heritage',
    },
    'Morocco': {
        'display_name': 'Morocco',
        'parent': 'North_African',
        'countries': ['Morocco'],
        'pc_coords': [-0.025, 0.025, -0.018, -0.010],
        'historical': 'Berber and Arab heritage',
    },
    'Algeria': {
        'display_name': 'Algeria',
        'parent': 'North_African',
        'countries': ['Algeria'],
        'pc_coords': [-0.028, 0.028, -0.020, -0.012],
        'historical': 'Berber and Arab heritage',
    },
    'Tunisia': {
        'display_name': 'Tunisia',
        'parent': 'North_African',
        'countries': ['Tunisia'],
        'pc_coords': [-0.022, 0.030, -0.015, -0.010],
        'historical': 'Phoenician, Berber, and Arab heritage',
    },
    'Libya': {
        'display_name': 'Libya',
        'parent': 'North_African',
        'countries': ['Libya'],
        'pc_coords': [-0.030, 0.032, -0.018, -0.014],
        'historical': 'Berber and Arab heritage',
    },
    'Egypt': {
        'display_name': 'Egypt',
        'parent': 'North_African',
        'countries': ['Egypt'],
        'pc_coords': [-0.035, 0.035, -0.012, -0.015],
        'historical': 'Ancient Egyptian and Arab heritage',
    },
    'African_Hunter_Gatherers': {
        'display_name': 'African Hunter-Gatherers',
        'parent': 'African',
        'countries': ['Multiple'],
        'pc_coords': [-0.100, -0.040, -0.005, 0.000],
        'historical': 'Khoisan and Pygmy peoples',
    },
    'Mauritius': {
        'display_name': 'Mauritius',
        'parent': 'East_African',
        'countries': ['Mauritius'],
        'pc_coords': [-0.065, -0.020, 0.010, 0.005],
        'historical': 'Mixed African, Indian, and European heritage',
    },

    # =========================================================================
    # EAST ASIA (15 regions)
    # =========================================================================
    'Northern_Han_Chinese': {
        'display_name': 'Northern Han Chinese',
        'parent': 'East_Asian',
        'countries': ['China'],
        'pc_coords': [-0.038, -0.052, 0.048, -0.022],
        'historical': 'Northern Chinese heritage',
    },
    'Southern_Han_Chinese': {
        'display_name': 'Southern Han Chinese',
        'parent': 'East_Asian',
        'countries': ['China'],
        'pc_coords': [-0.042, -0.055, 0.052, -0.025],
        'historical': 'Southern Chinese heritage',
    },
    'Japanese': {
        'display_name': 'Japan',
        'parent': 'East_Asian',
        'countries': ['Japan'],
        'pc_coords': [-0.036, -0.050, 0.055, -0.018],
        'historical': 'Jomon and Yayoi ancestry',
    },
    'Korean': {
        'display_name': 'Korea',
        'parent': 'East_Asian',
        'countries': ['South Korea', 'North Korea'],
        'pc_coords': [-0.037, -0.051, 0.052, -0.020],
        'historical': 'Korean Peninsula heritage',
    },
    'Mongolian': {
        'display_name': 'Mongolia & Central Asia',
        'parent': 'East_Asian',
        'countries': ['Mongolia'],
        'pc_coords': [-0.030, -0.045, 0.045, -0.010],
        'historical': 'Mongolic heritage',
    },
    'Tibetan': {
        'display_name': 'Tibet',
        'parent': 'East_Asian',
        'countries': ['China'],
        'pc_coords': [-0.035, -0.040, 0.042, -0.008],
        'historical': 'Tibetan Plateau heritage',
    },
    'Manchurian': {
        'display_name': 'Manchuria',
        'parent': 'East_Asian',
        'countries': ['China'],
        'pc_coords': [-0.034, -0.048, 0.046, -0.015],
        'historical': 'Manchu heritage',
    },
    'Vietnamese': {
        'display_name': 'Vietnam',
        'parent': 'Southeast_Asian',
        'countries': ['Vietnam'],
        'pc_coords': [-0.048, -0.050, 0.042, -0.016],
        'historical': 'Vietnamese Kinh heritage',
    },
    'Thai': {
        'display_name': 'Thailand',
        'parent': 'Southeast_Asian',
        'countries': ['Thailand'],
        'pc_coords': [-0.050, -0.048, 0.038, -0.012],
        'historical': 'Thai heritage',
    },
    'Filipino': {
        'display_name': 'Philippines',
        'parent': 'Southeast_Asian',
        'countries': ['Philippines'],
        'pc_coords': [-0.055, -0.052, 0.035, -0.010],
        'historical': 'Austronesian Filipino heritage',
    },
    'Indonesian': {
        'display_name': 'Indonesia',
        'parent': 'Southeast_Asian',
        'countries': ['Indonesia'],
        'pc_coords': [-0.058, -0.055, 0.032, -0.008],
        'historical': 'Austronesian Indonesian heritage',
    },
    'Malaysian': {
        'display_name': 'Malaysia',
        'parent': 'Southeast_Asian',
        'countries': ['Malaysia'],
        'pc_coords': [-0.052, -0.050, 0.036, -0.010],
        'historical': 'Malay heritage',
    },
    'Myanmar': {
        'display_name': 'Myanmar',
        'parent': 'Southeast_Asian',
        'countries': ['Myanmar'],
        'pc_coords': [-0.045, -0.045, 0.040, -0.008],
        'historical': 'Burmese heritage',
    },
    'Cambodia_Laos': {
        'display_name': 'Cambodia & Laos',
        'parent': 'Southeast_Asian',
        'countries': ['Cambodia', 'Laos'],
        'pc_coords': [-0.050, -0.048, 0.038, -0.010],
        'historical': 'Khmer and Lao heritage',
    },
    'Singapore': {
        'display_name': 'Singapore',
        'parent': 'Southeast_Asian',
        'countries': ['Singapore'],
        'pc_coords': [-0.050, -0.052, 0.040, -0.012],
        'historical': 'Chinese, Malay, and Indian heritage',
    },

    # =========================================================================
    # SOUTH ASIA (12 regions)
    # =========================================================================
    'Northern_India': {
        'display_name': 'Northern India',
        'parent': 'South_Asian',
        'countries': ['India'],
        'pc_coords': [-0.028, 0.025, 0.022, -0.006],
        'historical': 'Indo-Aryan heritage',
    },
    'Southern_India': {
        'display_name': 'Southern India',
        'parent': 'South_Asian',
        'countries': ['India'],
        'pc_coords': [-0.038, 0.018, 0.032, 0.002],
        'historical': 'Dravidian heritage',
    },
    'Punjabi': {
        'display_name': 'Punjab',
        'parent': 'South_Asian',
        'countries': ['India', 'Pakistan'],
        'pc_coords': [-0.025, 0.028, 0.020, -0.008],
        'historical': 'Punjabi heritage',
    },
    'Bengali': {
        'display_name': 'Bengal',
        'parent': 'South_Asian',
        'countries': ['Bangladesh', 'India'],
        'pc_coords': [-0.035, 0.020, 0.030, 0.000],
        'historical': 'Bengali heritage',
    },
    'Gujarati': {
        'display_name': 'Gujarat',
        'parent': 'South_Asian',
        'countries': ['India'],
        'pc_coords': [-0.030, 0.024, 0.025, -0.004],
        'historical': 'Gujarati heritage',
    },
    'Tamil': {
        'display_name': 'Tamil Nadu & Sri Lanka',
        'parent': 'South_Asian',
        'countries': ['India', 'Sri Lanka'],
        'pc_coords': [-0.040, 0.015, 0.035, 0.004],
        'historical': 'Tamil Dravidian heritage',
    },
    'Pakistan': {
        'display_name': 'Pakistan',
        'parent': 'South_Asian',
        'countries': ['Pakistan'],
        'pc_coords': [-0.024, 0.030, 0.018, -0.008],
        'historical': 'Pakistani heritage',
    },
    'Sri_Lanka': {
        'display_name': 'Sri Lanka',
        'parent': 'South_Asian',
        'countries': ['Sri Lanka'],
        'pc_coords': [-0.042, 0.016, 0.034, 0.003],
        'historical': 'Sinhalese and Tamil heritage',
    },
    'Nepal': {
        'display_name': 'Nepal',
        'parent': 'South_Asian',
        'countries': ['Nepal'],
        'pc_coords': [-0.032, 0.015, 0.035, 0.002],
        'historical': 'Nepali heritage',
    },
    'Kashmir': {
        'display_name': 'Kashmir',
        'parent': 'South_Asian',
        'countries': ['India', 'Pakistan'],
        'pc_coords': [-0.022, 0.032, 0.016, -0.010],
        'historical': 'Kashmiri heritage',
    },
    'Afghanistan': {
        'display_name': 'Afghanistan',
        'parent': 'South_Asian',
        'countries': ['Afghanistan'],
        'pc_coords': [-0.020, 0.035, 0.012, -0.010],
        'historical': 'Pashtun and Tajik heritage',
    },
    'Maldives': {
        'display_name': 'Maldives',
        'parent': 'South_Asian',
        'countries': ['Maldives'],
        'pc_coords': [-0.045, 0.012, 0.030, 0.005],
        'historical': 'Maldivian heritage',
    },

    # =========================================================================
    # AMERICAS (10 regions)
    # =========================================================================
    'Indigenous_Americas_North': {
        'display_name': 'Indigenous Americas—North',
        'parent': 'Native_American',
        'countries': ['USA', 'Canada'],
        'pc_coords': [-0.052, -0.062, 0.068, -0.038],
        'historical': 'North American Indigenous heritage',
    },
    'Indigenous_Americas_Mexico': {
        'display_name': 'Indigenous Americas—Mexico',
        'parent': 'Native_American',
        'countries': ['Mexico'],
        'pc_coords': [-0.055, -0.065, 0.072, -0.042],
        'historical': 'Mesoamerican Indigenous heritage',
    },
    'Indigenous_Americas_Central': {
        'display_name': 'Indigenous Americas—Central',
        'parent': 'Native_American',
        'countries': ['Guatemala', 'Honduras', 'El Salvador'],
        'pc_coords': [-0.058, -0.068, 0.075, -0.045],
        'historical': 'Central American Indigenous heritage',
    },
    'Indigenous_Americas_South': {
        'display_name': 'Indigenous Americas—South',
        'parent': 'Native_American',
        'countries': ['Peru', 'Bolivia', 'Ecuador'],
        'pc_coords': [-0.060, -0.070, 0.078, -0.048],
        'historical': 'South American Andean heritage',
    },
    'Indigenous_Caribbean': {
        'display_name': 'Indigenous Caribbean',
        'parent': 'Native_American',
        'countries': ['Caribbean'],
        'pc_coords': [-0.050, -0.060, 0.065, -0.035],
        'historical': 'Taino and Carib heritage',
    },
    'Indigenous_Amazon': {
        'display_name': 'Indigenous Amazonian',
        'parent': 'Native_American',
        'countries': ['Brazil', 'Peru', 'Colombia'],
        'pc_coords': [-0.062, -0.072, 0.080, -0.050],
        'historical': 'Amazonian Indigenous heritage',
    },
    'Indigenous_Yucatan': {
        'display_name': 'Indigenous Yucatan Peninsula',
        'parent': 'Native_American',
        'countries': ['Mexico', 'Guatemala', 'Belize'],
        'pc_coords': [-0.056, -0.066, 0.073, -0.043],
        'historical': 'Maya heritage',
    },
    'Indigenous_Andes': {
        'display_name': 'Indigenous Andes',
        'parent': 'Native_American',
        'countries': ['Peru', 'Bolivia', 'Chile'],
        'pc_coords': [-0.061, -0.071, 0.079, -0.049],
        'historical': 'Inca and Aymara heritage',
    },
    'Inuit_Yupik': {
        'display_name': 'Inuit & Yupik',
        'parent': 'Native_American',
        'countries': ['Canada', 'USA', 'Greenland'],
        'pc_coords': [-0.045, -0.055, 0.060, -0.030],
        'historical': 'Arctic Indigenous heritage',
    },
    'Greenlandic': {
        'display_name': 'Greenland',
        'parent': 'Native_American',
        'countries': ['Greenland'],
        'pc_coords': [-0.044, -0.054, 0.058, -0.028],
        'historical': 'Inuit Greenlandic heritage',
    },

    # =========================================================================
    # OCEANIA (8 regions)
    # =========================================================================
    'Eastern_Polynesia': {
        'display_name': 'Eastern Polynesia',
        'parent': 'Polynesian',
        'countries': ['Hawaii', 'Tahiti', 'Easter Island'],
        'pc_coords': [-0.058, -0.062, 0.048, -0.018],
        'historical': 'Polynesian voyager heritage',
    },
    'New_Zealand_Maori': {
        'display_name': 'New Zealand Māori',
        'parent': 'Polynesian',
        'countries': ['New Zealand'],
        'pc_coords': [-0.056, -0.060, 0.046, -0.016],
        'historical': 'Māori heritage',
    },
    'Samoa': {
        'display_name': 'Samoa',
        'parent': 'Polynesian',
        'countries': ['Samoa', 'American Samoa'],
        'pc_coords': [-0.055, -0.058, 0.044, -0.014],
        'historical': 'Samoan heritage',
    },
    'Tonga': {
        'display_name': 'Tonga',
        'parent': 'Polynesian',
        'countries': ['Tonga'],
        'pc_coords': [-0.054, -0.057, 0.043, -0.013],
        'historical': 'Tongan heritage',
    },
    'Fiji': {
        'display_name': 'Fiji',
        'parent': 'Melanesian',
        'countries': ['Fiji'],
        'pc_coords': [-0.062, -0.065, 0.030, 0.025],
        'historical': 'Fijian Melanesian heritage',
    },
    'Papua_New_Guinea': {
        'display_name': 'Papua New Guinea',
        'parent': 'Melanesian',
        'countries': ['Papua New Guinea'],
        'pc_coords': [-0.075, -0.075, 0.025, 0.045],
        'historical': 'Papuan heritage with Denisovan admixture',
    },
    'Aboriginal_Australian': {
        'display_name': 'Aboriginal Australian',
        'parent': 'Oceanian',
        'countries': ['Australia'],
        'pc_coords': [-0.080, -0.080, 0.020, 0.050],
        'historical': 'Aboriginal Australian heritage (50,000+ years)',
    },
    'Micronesian': {
        'display_name': 'Micronesia',
        'parent': 'Oceanian',
        'countries': ['Guam', 'Palau', 'FSM'],
        'pc_coords': [-0.060, -0.060, 0.040, -0.005],
        'historical': 'Micronesian heritage',
    },
    # =========================================================================
    # 1000 GENOMES POPULATION MAPPINGS (for ancestry engine compatibility)
    # =========================================================================
    'British': {
        'display_name': 'British',
        'parent': 'British_Isles',
        'countries': ['United Kingdom', 'England', 'Scotland', 'Wales'],
        'pc_coords': [0.022, -0.016, 0.002, 0.001],
        'historical': 'Anglo-Saxon, Celtic, and Norman heritage. The British population reflects waves of migration including Roman, Viking, and Norman influences.',
    },
    'Irish': {
        'display_name': 'Irish',
        'parent': 'British_Isles',
        'countries': ['Ireland'],
        'pc_coords': [0.027, -0.023, 0.006, 0.003],
        'historical': 'Gaelic Celtic heritage with ancient ties to the Atlantic seaboard populations.',
    },
    'Scottish': {
        'display_name': 'Scottish',
        'parent': 'British_Isles',
        'countries': ['Scotland'],
        'pc_coords': [0.025, -0.020, 0.005, 0.002],
        'historical': 'Mix of Celtic, Pictish, and Norse heritage.',
    },
    'Finnish': {
        'display_name': 'Finnish',
        'parent': 'Scandinavian',
        'countries': ['Finland'],
        'pc_coords': [0.040, -0.030, 0.025, 0.010],
        'historical': 'Unique Uralic heritage distinct from other Scandinavians, with genetic isolation contributing to distinctive traits.',
    },
    'Scandinavian': {
        'display_name': 'Scandinavian',
        'parent': 'Northern_European',
        'countries': ['Sweden', 'Norway', 'Denmark'],
        'pc_coords': [0.030, -0.025, 0.008, 0.005],
        'historical': 'Norse Viking heritage with Germanic roots.',
    },
    'German': {
        'display_name': 'German',
        'parent': 'Northwestern_European',
        'countries': ['Germany', 'Austria', 'Switzerland'],
        'pc_coords': [0.015, -0.010, 0.000, -0.002],
        'historical': 'Germanic tribal heritage (Franks, Saxons, Bavarians).',
    },
    'French': {
        'display_name': 'French',
        'parent': 'Northwestern_European',
        'countries': ['France', 'Belgium', 'Switzerland'],
        'pc_coords': [0.010, -0.005, -0.002, -0.003],
        'historical': 'Gaulish Celtic heritage with Frankish and Roman influences.',
    },
    'Northern_European': {
        'display_name': 'Northern European',
        'parent': 'European',
        'countries': ['Netherlands', 'Belgium', 'Germany', 'Denmark'],
        'pc_coords': [0.018, -0.012, 0.001, -0.001],
        'historical': 'Northwestern European heritage spanning the North Sea region.',
    },
    'Italian_Tuscan': {
        'display_name': 'Italian (Tuscan)',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [0.004, 0.012, -0.006, -0.003],
        'historical': 'Tuscan heritage from central Italy, with Etruscan and Roman roots.',
    },
    'Sicilian': {
        'display_name': 'Sicilian',
        'parent': 'Italian',
        'countries': ['Italy'],
        'pc_coords': [-0.005, 0.025, -0.010, -0.006],
        'historical': 'Greek, Arabic, Norman, and Spanish influences on this Mediterranean island.',
    },
    'Spanish_Iberian': {
        'display_name': 'Spanish/Iberian',
        'parent': 'Iberian',
        'countries': ['Spain', 'Portugal'],
        'pc_coords': [0.000, 0.008, -0.005, -0.002],
        'historical': 'Iberian heritage with Celtic, Roman, Visigothic, and Moorish influences.',
    },
    'Greek': {
        'display_name': 'Greek',
        'parent': 'Mediterranean',
        'countries': ['Greece', 'Cyprus'],
        'pc_coords': [-0.010, 0.025, -0.008, -0.005],
        'historical': 'Ancient Greek heritage, foundation of Western civilization.',
    },
    'Cypriot': {
        'display_name': 'Cypriot',
        'parent': 'Mediterranean',
        'countries': ['Cyprus'],
        'pc_coords': [-0.012, 0.028, -0.010, -0.006],
        'historical': 'Greek and Middle Eastern heritage on this Mediterranean island.',
    },
    'Maltese': {
        'display_name': 'Maltese',
        'parent': 'Italian',
        'countries': ['Malta'],
        'pc_coords': [-0.008, 0.028, -0.012, -0.008],
        'historical': 'Phoenician, Arabic, and Italian heritage.',
    },
    'Polish': {
        'display_name': 'Polish',
        'parent': 'Eastern_European',
        'countries': ['Poland'],
        'pc_coords': [0.020, -0.005, 0.010, 0.005],
        'historical': 'West Slavic heritage with Germanic and Baltic influences.',
    },
    'Russian': {
        'display_name': 'Russian',
        'parent': 'Eastern_European',
        'countries': ['Russia', 'Belarus', 'Ukraine'],
        'pc_coords': [0.025, 0.000, 0.015, 0.008],
        'historical': 'East Slavic heritage spanning the vast Eurasian territory.',
    },
    'Ashkenazi_Jewish': {
        'display_name': 'Ashkenazi Jewish',
        'parent': 'Jewish',
        'countries': ['Israel', 'USA', 'Europe'],
        'pc_coords': [0.005, 0.020, -0.015, -0.010],
        'historical': 'Jewish diaspora communities from Central and Eastern Europe, with Middle Eastern origins.',
    },
    'European': {
        'display_name': 'European',
        'parent': 'Eurasian',
        'countries': ['Europe'],
        'pc_coords': [0.015, 0.000, 0.000, 0.000],
        'historical': 'Broad European heritage spanning the continent.',
    },
    'African': {
        'display_name': 'African',
        'parent': 'African',
        'countries': ['Africa'],
        'pc_coords': [-0.050, 0.050, 0.000, 0.000],
        'historical': 'African heritage, the most genetically diverse population group on Earth.',
    },
    'East_Asian': {
        'display_name': 'East Asian',
        'parent': 'Asian',
        'countries': ['China', 'Japan', 'Korea', 'Mongolia'],
        'pc_coords': [-0.040, -0.040, -0.020, 0.000],
        'historical': 'East Asian heritage spanning China, Japan, Korea, and surrounding regions.',
    },
    'South_Asian': {
        'display_name': 'South Asian',
        'parent': 'Asian',
        'countries': ['India', 'Pakistan', 'Bangladesh', 'Sri Lanka'],
        'pc_coords': [-0.020, 0.010, 0.020, 0.015],
        'historical': 'South Asian heritage with ancient Indus Valley and Indo-Aryan influences.',
    },
    'Middle_Eastern': {
        'display_name': 'Middle Eastern',
        'parent': 'West_Asian',
        'countries': ['Saudi Arabia', 'UAE', 'Iraq', 'Syria', 'Jordan', 'Lebanon'],
        'pc_coords': [-0.015, 0.025, 0.010, 0.005],
        'historical': 'Middle Eastern heritage from the cradle of civilization.',
    },
    'Native_American': {
        'display_name': 'Native American',
        'parent': 'Indigenous_American',
        'countries': ['USA', 'Canada', 'Mexico'],
        'pc_coords': [-0.055, -0.045, -0.025, -0.010],
        'historical': 'Indigenous American heritage with ancient Asian migration origins.',
    },
    'Latino': {
        'display_name': 'Latino/Hispanic',
        'parent': 'American',
        'countries': ['Mexico', 'Central America', 'South America'],
        'pc_coords': [-0.030, 0.005, -0.010, -0.005],
        'historical': 'Mixed Indigenous American, European (primarily Spanish), and African heritage.',
    },
}

# Total count
TOTAL_POPULATIONS = len(REFERENCE_POPULATIONS)
print(f"Total reference populations: {TOTAL_POPULATIONS}") if __name__ == "__main__" else None
